# Generated by Django 5.0.3 on 2024-04-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('ethnicity', models.CharField(max_length=30)),
                ('veteran', models.BooleanField(default=False)),
                ('qada', models.BooleanField(default=False)),
                ('income', models.FloatField()),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('marital_status', models.CharField(choices=[('SI', 'Single'), ('MA', 'Married'), ('SE', 'Separated')], default='SI', max_length=2)),
                ('employment', models.CharField(max_length=100)),
                ('involvement', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
