# Generated by Django 4.1 on 2024-04-16 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AidSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='marital_status',
            field=models.CharField(choices=[('MA', 'Married'), ('SE', 'Separated'), ('SI', 'Single')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='info',
            name='year_in_school',
            field=models.CharField(choices=[('SR', 'Senior'), ('SO', 'Sophomore'), ('FR', 'Freshman'), ('JR', 'Junior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
