# Generated by Django 5.0.4 on 2024-04-23 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidSearch', '0002_alter_info_marital_status_alter_info_year_in_school_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='marital_status',
            field=models.CharField(choices=[('SE', 'Separated'), ('MA', 'Married'), ('SI', 'Single')], default='SI', max_length=2),
        ),
        migrations.AlterField(
            model_name='info',
            name='year_in_school',
            field=models.CharField(choices=[('GR', 'Graduate'), ('FR', 'Freshman'), ('SO', 'Sophomore'), ('SR', 'Senior'), ('JR', 'Junior')], default='FR', max_length=2),
        ),
    ]
