# Generated by Django 5.0.4 on 2024-04-23 16:54

import annoying.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidSearch', '0003_info_user_alter_info_marital_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='info',
            name='year_in_school',
            field=models.CharField(choices=[('SR', 'Senior'), ('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
